[build]
  command = "npm run build:web"
  publish = "dist/public"

[build.environment]
  NODE_VERSION = "22.18.0"

# Proxy API calls to the live API (avoids CORS and keeps same-origin cookies)
[[redirects]]
  from = "/api/*"
  to = "https://cleanandflip.onrender.com/api/:splat"
  status = 200
  force = true

# SPA fallback so client routing works on refresh/deep links
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Long-term caching for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Prevent caching of the entry HTML
[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

