services:
  # Backend API
  - type: web
    name: cleanfliprender-api
    runtime: node
    region: virginia
    rootDir: apps/api
    autoDeployTrigger: commit
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    healthCheckPath: /healthz
    envVars:
      - key: NODE_VERSION
        value: 22.16.0
      - key: APP_ENV
        value: production
      - key: FRONTEND_ORIGIN
        value: https://cleanfliprender-web.onrender.com
      - key: DATABASE_URL
        sync: false
      - key: SESSION_SECRET
        sync: false

  # Frontend (Static Site)
  - type: web
    name: cleanfliprender-web
    runtime: static
    region: virginia
    rootDir: apps/web
    autoDeployTrigger: commit
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
