[run]
command = "npm run dev"

[deployment]
run = "npm start"
publicDir = "dist/public"
deploymentTarget = "cloudrun"

[env]
NODE_ENV = "production"
PORT = "5000"

[development]
publicDir = "dist/public"