[deployment]
run = ["sh", "-c", "npm run dev"]

[languages]

[languages.typescript]
pattern = "**/{*.ts,*.js,*.tsx,*.jsx}"

  [languages.typescript.languageServer]
  start = "typescript-language-server --stdio"