[deployment]
run = ["npm", "run", "dev"]

[workspace]
entrypoint = "server/index.ts"

[languages]

[languages.typescript]
pattern = "**/{*.ts,*.js,*.tsx,*.jsx}"

  [languages.typescript.languageServer]
  start = "typescript-language-server --stdio"